name: Findora
categories:
  - infrastructure
description: >-
  A decentralized, privacy-preserving smart contract platform. Build the next
  privacy dApp for any EVM-chain with the world’s leading zero-knowledge
  technology-explore all new possibilities
product_readiness: mainnet, March 2021
links:
  web: https://findora.org
  github: https://github.com/findoranetwork
have_token: true
token:
  symbol: FRA
