name: Privatixy
categories:
  - infrastructure
description: >-
  An open-source protocol that offers a wide variety of solutions for privacy
  preservation for blockchain users.
product_readiness: TBD
links:
  web: https://privatixy.io
have_token: true
tokens:
  - symbol: PRIVATIXY
